services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_USER=pau
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3309:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql