package pau.coderhouse.example.entities;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;

@Entity
@Table(name = "clients")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Client {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id")
    @Schema(description = "Autogenerated UUID", requiredMode = Schema.RequiredMode.AUTO, example = "00000000-0000-0000-0000-000000000000")
    private String id;

    @Column(name = "name", nullable = false)
    @Schema(description = "Client´s name ", requiredMode = Schema.RequiredMode.REQUIRED, example = "Paulina")
    private String name;

    @Column(name = "lastname", nullable = false)
    @Schema(description = "Client´s last name", requiredMode = Schema.RequiredMode.REQUIRED, example = "Barcos")
    private String lastname;

    @Column(name = "dni", nullable = false, unique = true)
    @Schema(description = "Client´s DNI", requiredMode = Schema.RequiredMode.REQUIRED, example = "000.000.000")
    private int dni;

    @Column(name = "email", nullable = false, unique = true)
    @Schema(description = "Client´s email", requiredMode = Schema.RequiredMode.REQUIRED, example = "paulinabarcos@gmail.com")
    private String email;

    @OneToMany(mappedBy = "client", cascade = CascadeType.ALL)
    @JsonIgnoreProperties("client")
    @Schema(description = "We create the invoice and its relationship with the clients", requiredMode = Schema.RequiredMode.REQUIRED, example = "[{\"id\":\"00000000-0000-0000-0000-000000000000\",\"id\":\"2\",\"price\":25000,\"amount\":1,\"stock\":15,\"subtotal\":30.000}]")
    private List<Invoice> invoices;

}
